# -*- coding: utf-8 -*-
"""universal_pin.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A3lu-A9Z-8lhWh9WUa9Rp7aeLrLwN4au

# Dependencies
"""

import pickle
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from scipy import stats
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import pandas as pd

"""# De-serializing data"""

pin = pickle.load(open('serialized files/pin.pkl', 'rb'))
pin

"""# Preprocessing"""

pin = pin[['user_id', 'TotalTransactionAmount', 'Tx_Count', 'DaysSinceLastTrans']]
pin

pin.describe()

pin_customers = pin.groupby(['user_id']).agg({
    'TotalTransactionAmount': 'sum',
    'Tx_Count': 'count',
    'DaysSinceLastTrans' : 'sum'
})

pin_customers.rename(columns={'TotalTransactionAmount': 'Amount',
                                 'Tx_Count': 'Freq',
                                'DaysSinceLastTrans': 'Re'}, inplace=True)
pin_customers

print(pin_customers.Re.skew())
print(pin_customers.Freq.skew())
print(pin_customers.Amount.skew())

"""## Converting Data to Gaussian Distribution

### Visualization
"""

import warnings
warnings.filterwarnings('ignore')

fig, ax = plt.subplots(2, 2, figsize=(12, 7))

fig = sns.distplot(pin_customers.Re, color='b', ax=ax[0, 0])
fig = sns.distplot(pin_customers.Amount, color='g', ax=ax[0, 1])
fig = sns.distplot(pin_customers.Freq, color='y', ax=ax[1, 0])
ax[0, 0].set_title('Recency')
ax[0, 1].set_title('Income')
ax[1, 0].set_title('Frequency')

plt.tight_layout()
plt.show()

"""### Log Transformation"""

log_trans = pd.DataFrame()
log_trans['Amount'] = np.log(pin_customers['Amount'])
log_trans['Freq'] = np.log(pin_customers['Freq'])
log_trans['Re'] = np.log(pin_customers['Re'])

print(log_trans.Re.skew())
print(log_trans.Freq.skew())
print(log_trans.Amount.skew())

"""#### After-Log-Transformation"""

fig, ax = plt.subplots(2, 2, figsize=(12, 7))

fig = sns.distplot(log_trans.Re, color='b', ax=ax[0, 0])
fig = sns.distplot(log_trans.Amount, color='g', ax=ax[0, 1])
fig = sns.distplot(log_trans.Freq, color='y', ax=ax[1, 0])
ax[0, 0].set_title('Recency')
ax[0, 1].set_title('Income')
ax[1, 0].set_title('Frequency')

plt.tight_layout()
plt.show()

"""### BoxCox Transfromation"""

boxcox_trans = pd.DataFrame()
boxcox_trans['Amount'] = stats.boxcox(pin_customers['Amount'])[0]
boxcox_trans['Freq'] = stats.boxcox(pin_customers['Freq'])[0]
boxcox_trans['Re'] = stats.boxcox(pin_customers['Re'])[0]

print(boxcox_trans.Re.skew())
print(boxcox_trans.Freq.skew())
print(boxcox_trans.Amount.skew())

"""#### After-Boxcox-Transformation"""

fig, ax = plt.subplots(2, 2, figsize=(12, 7))

fig = sns.distplot(boxcox_trans.Re, color='b', ax=ax[0, 0])
fig = sns.distplot(boxcox_trans.Amount, color='g', ax=ax[0, 1])
fig = sns.distplot(boxcox_trans.Freq, color='y', ax=ax[1, 0])
ax[0, 0].set_title('Recency')
ax[0, 1].set_title('Income')
ax[1, 0].set_title('Frequency')

plt.tight_layout()
plt.show()

"""### Cubic Root Transformation"""

square_trans = pd.DataFrame()
square_trans['Amount'] = np.cbrt(pin_customers['Amount'])
square_trans['Freq'] = np.cbrt(pin_customers['Freq'])
square_trans['Re'] = np.cbrt(pin_customers['Re'])

print(square_trans.Re.skew())
print(square_trans.Freq.skew())
print(square_trans.Amount.skew())

"""#### After-Cubic-Root-Transformation"""

fig, ax = plt.subplots(2, 2, figsize=(12, 7))

fig = sns.distplot(square_trans.Re, color='b', ax=ax[0, 0])
fig = sns.distplot(square_trans.Amount, color='g', ax=ax[0, 1])
fig = sns.distplot(square_trans.Freq, color='y', ax=ax[1, 0])
ax[0, 0].set_title('Recency')
ax[0, 1].set_title('Income')
ax[1, 0].set_title('Frequency')

plt.tight_layout()
plt.show()

"""<b>BOX COX Transfroms the Data Better</b>

### Normalization
"""

scale = StandardScaler()
scale.fit(boxcox_trans)
pin_normalized = scale.transform(boxcox_trans)

fig, ax = plt.subplots(2, 2, figsize=(12, 7))

fig = sns.distplot(pin_normalized[0], color='b', ax=ax[0, 0])
fig = sns.distplot(pin_normalized[1], color='g', ax=ax[0, 1])
fig = sns.distplot(pin_normalized[2], color='y', ax=ax[1, 0])
ax[0, 0].set_title('Recency')
ax[0, 1].set_title('Income')
ax[1, 0].set_title('Frequency')

plt.tight_layout()
plt.show()

print(pin_normalized.mean(axis = 0).round(2))
print(pin_normalized.std(axis = 0).round(2))

"""# Clustering

## Hyperparameter Tuning using the Elbow Method
"""

sse = {}

for k in range(1, 6):
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(pin_normalized)
    sse[k] = kmeans.inertia_
plt.title('The Elbow Method')
plt.xlabel('Number of Clusters')
plt.ylabel('Sum of Squared Distance')
sns.pointplot(x=list(sse.keys()), y=list(sse.values()))
plt.show()

model = KMeans(n_clusters=3, random_state=42)
model.fit(pin_normalized)
model.labels_

"""## Matching labels with each customer"""

pin_customers["Cluster"] = model.labels_
pin_customers.groupby('Cluster').agg({
    'Re':'mean',
    'Freq':'mean',
    'Amount':['mean', 'count']}).round(2)
pin_customers

"""## Melting the Dataframe"""

df_normalized = pd.DataFrame(pin_normalized, columns=['Re', 'Freq', 'Amount'])
df_normalized['Cust ID'] = pin_customers.index
df_normalized['Cluster'] = model.labels_

df_nor_melt = pd.melt(df_normalized.reset_index(),
                      id_vars=['Cust ID', 'Cluster'],
                      value_vars=['Re','Freq','Amount'],
                      var_name='Attribute',
                      value_name='Value')
df_nor_melt

"""### Visualization"""

plt.figure(figsize=(15, 8))
sns.lineplot('Attribute', 'Value', hue='Cluster', data=df_nor_melt)
plt.show()